language: python
python:
  - "3.7"
services:
  - mysql
install:
  - pip install -r requirements.txt
before_script:
  - mysql -e 'create database tennis;'
  - cp tennis/settings.py.sample tennis/settings.py
script: python manage.py test