version: '3'

services:
  db:
    image: mariadb:10.1
    restart: always
    env_file:
      - ./.env.dev
    volumes:
      - ./data/db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: ["./docker/web/wait-for-it.sh", "db:3306", "--", "python", "./manage.py", "runserver", "0.0.0.0:8000"]
    env_file:
      - ./.env.dev
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db