version: '3'

services:
  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    env_file:
      - ./.env.prod
    command: /bin/sh -c "envsubst '\$$NGINX_HOST' < /etc/nginx/conf.d/app.conf.template > /etc/nginx/conf.d/app.conf
      && htpasswd -nb $$ADMINER_USER $$ADMINER_PASSWORD > /etc/nginx/conf.d/.adminer.htpasswd
      && while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;'"
    depends_on:
      - web
      - adminer
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  db:
    image: mariadb:10.1
    restart: always
    env_file:
      - ./.env.prod
    volumes:
      - ./data/db:/var/lib/mysql
  adminer:
    image: adminer:4-fastcgi
    restart: always
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: ["./docker/web/wait-for-it.sh", "db:3306", "--", "gunicorn", "tennis.wsgi:application", "--bind", "0.0.0.0:8000"]
    env_file:
      - ./.env.prod
    volumes:
      - .:/code
    depends_on:
      - db